INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add log entry', 1, 'add_logentry');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change log entry', 1, 'change_logentry');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete log entry', 1, 'delete_logentry');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add permission', 2, 'add_permission');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change permission', 2, 'change_permission');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete permission', 2, 'delete_permission');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add group', 3, 'add_group');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change group', 3, 'change_group');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete group', 3, 'delete_group');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add user', 4, 'add_user');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change user', 4, 'change_user');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete user', 4, 'delete_user');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add content type', 5, 'add_contenttype');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change content type', 5, 'change_contenttype');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete content type', 5, 'delete_contenttype');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add session', 6, 'add_session');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change session', 6, 'change_session');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete session', 6, 'delete_session');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add revision', 7, 'add_revision');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change revision', 7, 'change_revision');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete revision', 7, 'delete_revision');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add version', 8, 'add_version');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change version', 8, 'change_version');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete version', 8, 'delete_version');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add user social auth', 9, 'add_usersocialauth');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change user social auth', 9, 'change_usersocialauth');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete user social auth', 9, 'delete_usersocialauth');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add nonce', 10, 'add_nonce');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change nonce', 10, 'change_nonce');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete nonce', 10, 'delete_nonce');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add association', 11, 'add_association');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change association', 11, 'change_association');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete association', 11, 'delete_association');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add code', 12, 'add_code');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change code', 12, 'change_code');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete code', 12, 'delete_code');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add partial', 13, 'add_partial');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change partial', 13, 'change_partial');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete partial', 13, 'delete_partial');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add 栏目', 14, 'add_category');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change 栏目', 14, 'change_category');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete 栏目', 14, 'delete_category');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add 标签', 15, 'add_tag');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change 标签', 15, 'change_tag');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete 标签', 15, 'delete_tag');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add 文章', 16, 'add_article');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change 文章', 16, 'change_article');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete 文章', 16, 'delete_article');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add 评论', 17, 'add_comment');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change 评论', 17, 'change_comment');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete 评论', 17, 'delete_comment');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add 收藏夹', 18, 'add_favoritecategory');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change 收藏夹', 18, 'change_favoritecategory');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete 收藏夹', 18, 'delete_favoritecategory');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add 收藏', 19, 'add_favorite');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change 收藏', 19, 'change_favorite');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete 收藏', 19, 'delete_favorite');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add 用户反馈', 20, 'add_feedback');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change 用户反馈', 20, 'change_feedback');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete 用户反馈', 20, 'delete_feedback');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add 信息', 21, 'add_message');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change 信息', 21, 'change_message');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete 信息', 21, 'delete_message');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add 专题', 23, 'add_active');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change 专题', 23, 'change_active');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete 专题', 23, 'delete_active');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add 专题-文章', 25, 'add_activearticle');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change 专题-文章', 25, 'change_activearticle');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete 专题-文章', 25, 'delete_activearticle');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add 专题-友情链接', 26, 'add_activefriendlink');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change 专题-友情链接', 26, 'change_activefriendlink');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete 专题-友情链接', 26, 'delete_activefriendlink');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add 专题', 27, 'add_active');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change 专题', 27, 'change_active');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete 专题', 27, 'delete_active');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add 专题-友情链接', 28, 'add_activefriendlink');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change 专题-友情链接', 28, 'change_activefriendlink');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete 专题-友情链接', 28, 'delete_activefriendlink');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can add 自定义显示', 29, 'add_userdefined');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can change 自定义显示', 29, 'change_userdefined');
INSERT INTO yunjiu.auth_permission (name, content_type_id, codename) VALUES ('Can delete 自定义显示', 29, 'delete_userdefined');