# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 12:17
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setting', '0002_auto_20170415_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('title', models.CharField(default=b'', max_length=128, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('mark', models.CharField(default=b'', max_length=100, verbose_name=b'\xe7\x9f\xad\xe6\xa0\x87\xe9\xa2\x98')),
                ('description', models.CharField(blank=True, default=b'', max_length=500, null=True, verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='\u5185\u5bb9')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name=b'\xe5\xb0\x81\xe9\x9d\xa2')),
                ('publish_at', models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 15, 20, 17, 51, 75571), null=True, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xb6\xe9\x97\xb4')),
                ('short_story', models.IntegerField(choices=[(0, b'\xe5\x90\xa6'), (1, b'\xe6\x98\xaf')], default=0, verbose_name=b'\xe6\x97\xa9\xe7\x9f\xa5\xe9\x81\x93')),
                ('status', models.IntegerField(choices=[(0, b'\xe8\x8d\x89\xe7\xa8\xbf'), (1, b'\xe5\xae\xa1\xe6\xa0\xb8\xe4\xb8\xad'), (2, b'\xe5\xae\xa1\xe6\xa0\xb8\xe9\x80\x9a\xe8\xbf\x87'), (3, b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (4, b'\xe5\xb7\xb2\xe5\x88\xa0\xe9\x99\xa4')], default=0, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('auth_way', models.IntegerField(choices=[(1, b'\xe5\xbe\xae\xe4\xbf\xa1\xe5\x8e\x9f\xe5\x88\x9b\xe6\xa0\x87\xe7\x8b\xac\xe5\xae\xb6\xe6\x8e\x88\xe6\x9d\x83'), (2, b'\xe5\xbe\xae\xe4\xbf\xa1\xe7\x99\xbd\xe5\x90\x8d\xe5\x8d\x95\xe6\x8e\x88\xe6\x9d\x83 ')], default=1, verbose_name=b'\xe5\xbe\xae\xe4\xbf\xa1\xe6\x8e\x88\xe6\x9d\x83')),
                ('auth_reprinted', models.IntegerField(choices=[(0, b'\xe5\x90\xa6'), (1, b'\xe6\x98\xaf')], default=0, verbose_name=b'\xe5\x8e\x9f\xe5\x88\x9b\xe6\xa0\x87\xe7\xa4\xba')),
                ('tag', models.IntegerField(choices=[(0, b'\xe5\x90\xa6'), (1, b'\xe6\x98\xaf')], default=0, verbose_name=b'\xe5\x8c\xbf\xe5\x90\x8d\xe6\x8a\x95\xe7\xa8\xbf')),
                ('article_memo', models.IntegerField(blank=True, null=True, verbose_name=b'\xe8\x81\x94\xe7\xb3\xbb\xe6\x96\xb9\xe5\xbc\x8f')),
                ('show_in_home', models.IntegerField(choices=[(0, b'\xe5\x90\xa6'), (1, b'\xe6\x98\xaf')], default=0, verbose_name=b'\xe6\x98\xbe\xe7\xa4\xba\xe5\x88\xb0\xe9\xa6\x96\xe9\xa1\xb5')),
                ('top_in_home', models.IntegerField(choices=[(0, b'\xe5\x90\xa6'), (1, b'\xe6\x98\xaf')], default=0, verbose_name=b'\xe9\xa6\x96\xe9\xa1\xb5\xe7\xbd\xae\xe9\xa1\xb6')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='c_articles', to='setting.Category', verbose_name=b'\xe6\xa0\x8f\xe7\x9b\xae')),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='u_articles', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85')),
                ('likes', models.ManyToManyField(blank=True, related_name='u_articles_liked', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\x82\xb9\xe8\xb5\x9e\xe8\x80\x85\xe5\x88\x97\xe8\xa1\xa8')),
            ],
            options={
                'db_table': 'article',
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('content', models.TextField(verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_comments', to='article.Article', verbose_name=b'\xe6\x96\x87\xe7\xab\xa0')),
                ('at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='at_comments', to=settings.AUTH_USER_MODEL, verbose_name=b'@\xe4\xba\x86\xe8\xb0\x81')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_comments', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe8\x80\x85')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_comments', to='article.Comment')),
            ],
            options={
                'db_table': 'article_comments',
                'verbose_name': '\u8bc4\u8bba',
                'verbose_name_plural': '\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_favorites', to='article.Article', verbose_name=b'\xe6\x96\x87\xe7\xab\xa0')),
            ],
            options={
                'db_table': 'favorite',
                'verbose_name': '\u6536\u85cf',
                'verbose_name_plural': '\u6536\u85cf',
            },
        ),
        migrations.CreateModel(
            name='FavoriteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('name', models.CharField(max_length=255, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_favorite_categories', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe8\x80\x85')),
            ],
            options={
                'db_table': 'favorite_category',
                'verbose_name': '\u6536\u85cf\u5939',
                'verbose_name_plural': '\u6536\u85cf\u5939',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
            options={
                'db_table': 'source',
                'verbose_name': ' \u6765\u6e90',
                'verbose_name_plural': ' \u6765\u6e90',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0')),
            ],
            options={
                'db_table': 'tag',
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.AddField(
            model_name='favorite',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_favorites', to='article.FavoriteCategory', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe6\x94\xb6\xe8\x97\x8f\xe5\xa4\xb9'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_favorites', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe6\x94\xb6\xe8\x97\x8f\xe8\x80\x85'),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Source', verbose_name=b'\xe6\x9d\xa5\xe6\xba\x90'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='t_articles', to='article.Tag', verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe\xe5\x88\x97\xe8\xa1\xa8'),
        ),
    ]
