# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 12:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170415_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='editor',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_editor_articles', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\xbc\x96\xe8\xbe\x91'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 15, 20, 30, 3, 377863), null=True, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
