# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 15:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20170415_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='top_in_home_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'\xe8\xae\xbe\xe7\xbd\xae/\xe5\x8f\x96\xe6\xb6\x88\xe7\xbd\xae\xe9\xa1\xb6\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 15, 23, 45, 9, 286702), null=True, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
