# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 09:21
from __future__ import unicode_literals

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('active', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('name', models.CharField(max_length=32, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
                ('key', models.CharField(blank=True, max_length=32, null=True, verbose_name=b'\xe6\xa0\x87\xe8\xaf\x86')),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('status', models.IntegerField(choices=[(0, b'\xe4\xb8\x93\xe9\xa2\x98\xe6\xa0\x8f\xe7\x9b\xae'), (1, b'\xe6\x99\xae\xe9\x80\x9a\xe6\xa0\x8f\xe7\x9b\xae')], default=1, verbose_name=b'\xe6\x99\xae\xe9\x80\x9a\xe6\xa0\x8f\xe7\x9b\xae/\xe4\xb8\x93\xe9\xa2\x98\xe6\xa0\x8f\xe7\x9b\xae')),
                ('show_num', models.IntegerField(default=5, verbose_name=b'\xe6\x98\xbe\xe7\xa4\xba\xe6\x95\xb0\xe9\x87\x8f(\xe4\xb8\x93\xe9\xa2\x98\xe6\xa0\x8f\xe7\x9b\xae\xe9\x99\x90\xe5\x88\xb6\xe6\x95\xb0\xe9\x87\x8f\xe7\x94\xa8)')),
                ('top_no', models.IntegerField(choices=[(0, b''), (10, b'\xe7\xac\xac\xe4\xb8\x80\xe4\xbd\x8d'), (9, b'\xe7\xac\xac\xe4\xba\x8c\xe4\xbd\x8d'), (8, b'\xe7\xac\xac\xe4\xb8\x89\xe4\xbd\x8d'), (7, b'\xe7\xac\xac\xe5\x9b\x9b\xe4\xbd\x8d'), (6, b'\xe7\xac\xac\xe4\xba\x94\xe4\xbd\x8d'), (5, b'\xe7\xac\xac\xe5\x85\xad\xe4\xbd\x8d'), (4, b'\xe7\xac\xac\xe4\xb8\x83\xe4\xbd\x8d'), (3, b'\xe7\xac\xac\xe5\x85\xab\xe4\xbd\x8d'), (2, b'\xe7\xac\xac\xe4\xb9\x9d\xe4\xbd\x8d'), (1, b'\xe7\xac\xac\xe5\x8d\x81\xe4\xbd\x8d')], default=0, verbose_name=b'\xe5\x85\x88\xe5\x90\x8e\xe9\xa1\xba\xe5\xba\x8f')),
                ('active', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='at_categories', to='active.Active', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe4\xb8\x93\xe9\xa2\x98')),
            ],
            options={
                'db_table': 'category',
                'verbose_name': '\u680f\u76ee',
                'verbose_name_plural': '\u680f\u76ee',
            },
        ),
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('title', models.CharField(max_length=255, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('href', models.CharField(max_length=300, verbose_name=b'\xe9\x93\xbe\xe6\x8e\xa5')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87')),
            ],
            options={
                'db_table': 'companion',
                'verbose_name': '\u5408\u4f5c\u4f19\u4f34',
                'verbose_name_plural': '\u5408\u4f5c\u4f19\u4f34',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('content', models.TextField(verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('contact', models.CharField(default=b'', max_length=255, verbose_name=b'\xe8\x81\x94\xe7\xb3\xbb\xe6\x96\xb9\xe5\xbc\x8f')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe8\x80\x85')),
            ],
            options={
                'db_table': 'feedback',
                'verbose_name': '\u7528\u6237\u53cd\u9988',
                'verbose_name_plural': '\u7528\u6237\u53cd\u9988',
            },
        ),
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('title', models.CharField(max_length=255, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('href', models.CharField(max_length=300, verbose_name=b'\xe9\x93\xbe\xe6\x8e\xa5')),
            ],
            options={
                'db_table': 'friend_link',
                'verbose_name': '\u53cb\u60c5\u94fe\u63a5',
                'verbose_name_plural': '\u53cb\u60c5\u94fe\u63a5',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('content', models.TextField(verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('type', models.IntegerField(choices=[(0, b'\xe7\xa7\x81\xe4\xbf\xa1'), (1, b'\xe7\xb3\xbb\xe7\xbb\x9f\xe4\xbf\xa1\xe6\x81\xaf')], verbose_name=b'\xe4\xbf\xa1\xe6\x81\xaf\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_send_msgs', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x8f\x91\xe9\x80\x81\xe8\x80\x85')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_receive_msgs', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe6\x8e\xa5\xe5\x8f\x97\xe8\x80\x85')),
            ],
            options={
                'db_table': 'message',
                'verbose_name': '\u4fe1\u606f',
                'verbose_name_plural': '\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='UserDefined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('type', models.IntegerField(choices=[(0, b'\xe5\x85\xb3\xe4\xba\x8e\xe6\x88\x91\xe4\xbb\xac'), (1, b'\xe5\x8a\xa0\xe5\x85\xa5\xe6\x88\x91\xe4\xbb\xac'), (2, b'\xe5\x90\x88\xe4\xbd\x9c\xe4\xbc\x99\xe4\xbc\xb4'), (3, b'\xe5\x8f\x8b\xe6\x83\x85\xe9\x93\xbe\xe6\x8e\xa5'), (4, b'\xe5\xb9\xbf\xe5\x91\x8a\xe5\x8f\x8a\xe6\x9c\x8d\xe5\x8a\xa1'), (5, b'\xe5\xb8\xb8\xe8\xa7\x81\xe9\x97\xae\xe9\xa2\x98\xe8\xa7\xa3\xe7\xad\x94')], verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='\u5185\u5bb9')),
                ('status', models.IntegerField(choices=[(0, b'\xe5\x90\xa6'), (1, b'\xe6\x98\xaf')], default=1, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x8f\x91\xe5\xb8\x83')),
            ],
            options={
                'db_table': 'user_defined',
                'verbose_name': '\u81ea\u5b9a\u4e49\u663e\u793a',
                'verbose_name_plural': '\u81ea\u5b9a\u4e49\u663e\u793a',
            },
        ),
    ]
