# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 10:47
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdefined',
            name='content1',
            field=models.TextField(blank=True, null=True, verbose_name='\u7b80\u5355\u6587\u672c'),
        ),
        migrations.AlterField(
            model_name='userdefined',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='\u5bcc\u6587\u672c\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='userdefined',
            name='type',
            field=models.IntegerField(choices=[(0, b'\xe5\x85\xb3\xe4\xba\x8e\xe6\x88\x91\xe4\xbb\xac'), (1, b'\xe5\x8a\xa0\xe5\x85\xa5\xe6\x88\x91\xe4\xbb\xac'), (2, b'\xe5\x90\x88\xe4\xbd\x9c\xe4\xbc\x99\xe4\xbc\xb4'), (3, b'\xe5\x8f\x8b\xe6\x83\x85\xe9\x93\xbe\xe6\x8e\xa5'), (4, b'\xe5\xb9\xbf\xe5\x91\x8a\xe5\x8f\x8a\xe6\x9c\x8d\xe5\x8a\xa1'), (5, b'\xe5\xb8\xb8\xe8\xa7\x81\xe9\x97\xae\xe9\xa2\x98\xe8\xa7\xa3\xe7\xad\x94'), (6, b'metas')], verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
    ]
