# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('mark', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xe7\x9f\xad\xe6\xa0\x87\xe9\xa2\x98')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name=b'\xe5\xb0\x81\xe9\x9d\xa2')),
                ('backgroud', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name=b'\xe8\x83\x8c\xe6\x99\xaf\xe5\x9b\xbe')),
                ('time_table', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name=b'\xe6\x97\xb6\xe5\x88\xbb\xe8\xa1\xa8')),
                ('guanggao_title', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xe5\xb9\xbf\xe5\x91\x8a\xe4\xbd\x8d\xe6\xa0\x87\xe9\xa2\x98')),
                ('guanggao_pic', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name=b'\xe5\xb9\xbf\xe5\x91\x8a\xe4\xbd\x8d\xe5\x9b\xbe\xe7\x89\x87')),
                ('guanggao_href', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xe5\xb9\xbf\xe5\x91\x8a\xe4\xbd\x8d\xe9\x93\xbe\xe6\x8e\xa5')),
                ('status', models.IntegerField(choices=[(0, b'\xe6\x9c\xaa\xe5\x8f\x91\xe5\xb8\x83'), (1, b'\xe8\xbf\x9b\xe8\xa1\x8c\xe4\xb8\xad'), (2, b'\xe5\xb7\xb2\xe7\xbb\x93\xe6\x9d\x9f')], default=0, verbose_name=b' \xe7\x8a\xb6\xe6\x80\x81')),
            ],
            options={
                'db_table': 'active',
                'verbose_name': '\u4e13\u9898',
                'verbose_name_plural': '\u4e13\u9898',
            },
        ),
        migrations.CreateModel(
            name='ActiveFriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('title', models.CharField(max_length=255, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('href', models.CharField(max_length=300, verbose_name=b'\xe9\x93\xbe\xe6\x8e\xa5')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87')),
                ('active', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='at_links', to='active.Active', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe4\xb8\x93\xe9\xa2\x98')),
            ],
            options={
                'db_table': 'active_friend_link',
                'verbose_name': '\u4e13\u9898-\u53cb\u60c5\u94fe\u63a5',
                'verbose_name_plural': '\u4e13\u9898-\u53cb\u60c5\u94fe\u63a5',
            },
        ),
    ]
